<?php

namespace ContainerYPrdLHK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMoneyControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MoneyController' shared autowired service.
     *
     * @return \App\Controller\MoneyController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/MoneyController.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Money/InsertMoneyUseCase.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Money/MoneyRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/FileMoneyRepository.php';

        $container->services['App\\Controller\\MoneyController'] = $instance = new \App\Controller\MoneyController(new \App\Application\Money\InsertMoneyUseCase(new \App\Infrastructure\Persistence\FileMoneyRepository()));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\MoneyController', $container));

        return $instance;
    }
}
