<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_health' => [[], ['_controller' => 'App\\Controller\\HealthController::health'], [], [['text', '/api/health']], [], [], []],
    'api_items_list' => [[], ['_controller' => 'App\\Controller\\ItemController::list'], [], [['text', '/api/items']], [], [], []],
    'api_items_show' => [['id'], ['_controller' => 'App\\Controller\\ItemController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/items']], [], [], []],
    'api_items_create' => [[], ['_controller' => 'App\\Controller\\ItemController::create'], [], [['text', '/api/items']], [], [], []],
    'api_items_update' => [['id'], ['_controller' => 'App\\Controller\\ItemController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/items']], [], [], []],
    'api_items_delete' => [['id'], ['_controller' => 'App\\Controller\\ItemController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/items']], [], [], []],
    'api_purchase_create' => [[], ['_controller' => 'App\\Controller\\PurchaseController::create'], [], [['text', '/api/purchase']], [], [], []],
    'App\Controller\HealthController::health' => [[], ['_controller' => 'App\\Controller\\HealthController::health'], [], [['text', '/api/health']], [], [], []],
    'App\Controller\ItemController::list' => [[], ['_controller' => 'App\\Controller\\ItemController::list'], [], [['text', '/api/items']], [], [], []],
    'App\Controller\ItemController::show' => [['id'], ['_controller' => 'App\\Controller\\ItemController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/items']], [], [], []],
    'App\Controller\ItemController::create' => [[], ['_controller' => 'App\\Controller\\ItemController::create'], [], [['text', '/api/items']], [], [], []],
    'App\Controller\ItemController::update' => [['id'], ['_controller' => 'App\\Controller\\ItemController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/items']], [], [], []],
    'App\Controller\ItemController::delete' => [['id'], ['_controller' => 'App\\Controller\\ItemController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/items']], [], [], []],
    'App\Controller\PurchaseController::create' => [[], ['_controller' => 'App\\Controller\\PurchaseController::create'], [], [['text', '/api/purchase']], [], [], []],
];
